# Generated by Django 4.2.1 on 2023-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Galaxia', 'Galaxia'), ('Estrela', 'Estrela'), ('Nebulosa', 'Nebulosa'), ('Lua', 'Lua'), ('Planeta', 'Planeta')], default='Galaxia', max_length=20),
        ),
    ]
